DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
 id INT PRIMARY KEY,
 first_name VARCHAR(250) NOT NULL,
 last_name VARCHAR(250) NOT NULL,
 email VARCHAR(250) NOT NULL,
 avatar VARCHAR(400) NOT NULL);

 DROP TABLE IF EXISTS RESOURCES;

 CREATE TABLE RESOURCES(
  id INT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  year_of_creation INT NOT NULL,
  color VARCHAR(250) NOT NULL,
  pantone_value VARCHAR(250) NOT NULL);